// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1mETWKyOA-3vodUvSCLyksFOFxM5acLY',
    appId: '1:101036656477:web:ebf51a93e7eea084b8cab4',
    messagingSenderId: '101036656477',
    projectId: 'flutter-spotify-cl',
    authDomain: 'flutter-spotify-cl.firebaseapp.com',
    storageBucket: 'flutter-spotify-cl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4HZnir4yK83732ed4KfDY5yx1yiBkwrU',
    appId: '1:101036656477:android:f8481200f9698831b8cab4',
    messagingSenderId: '101036656477',
    projectId: 'flutter-spotify-cl',
    storageBucket: 'flutter-spotify-cl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzkfbprJbz9OJ8sQ4HgMdiU07aZutPpqk',
    appId: '1:101036656477:ios:b63b5352a7ae4c18b8cab4',
    messagingSenderId: '101036656477',
    projectId: 'flutter-spotify-cl',
    storageBucket: 'flutter-spotify-cl.firebasestorage.app',
    iosBundleId: 'com.example.flutterSpotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzkfbprJbz9OJ8sQ4HgMdiU07aZutPpqk',
    appId: '1:101036656477:ios:b63b5352a7ae4c18b8cab4',
    messagingSenderId: '101036656477',
    projectId: 'flutter-spotify-cl',
    storageBucket: 'flutter-spotify-cl.firebasestorage.app',
    iosBundleId: 'com.example.flutterSpotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1mETWKyOA-3vodUvSCLyksFOFxM5acLY',
    appId: '1:101036656477:web:7acc5ce29f9793d6b8cab4',
    messagingSenderId: '101036656477',
    projectId: 'flutter-spotify-cl',
    authDomain: 'flutter-spotify-cl.firebaseapp.com',
    storageBucket: 'flutter-spotify-cl.firebasestorage.app',
  );
}
